### ISSUE TITLE
Create a Simple WebApp for Forest Fire Prediction 👨‍💻

### ISSUE THREAD

**Issue by soumya997** [dsc-iem/AI-Hacktoberfest#10]
Hey, @Nibba2018 and @BALaka-18 I have created this issue to give a direction to this small project.

Now, we have already done the Data analysis and Model building using the forest fire dataset.
In data analysis, we have covered Uni-variate, Bi-variate, and Multi-variate analysis of the data.
In the model Building part, we have made a Regression model using Random Forest Regressor.

Now, if we can **give a direction to all the analysis and model building parts** that we have done by making a small **web app** for forest fire prediction using basic flask or streamlet and any beginner-friendly hosting platform(_Heroku or Ngrok or Netlify_) that will help this project to complete the whole **life cycle of a Data Science project**.

Let me know it is acceptable or not.

**Comment by Nibba2018** [comment]
Sounds like a good idea @soumya997 , what exactly do you have in mind?

**Comment by soumya997** [comment]
just pushing the model for deployment, as a webapp using flask or streamlet and hosting that in some basic platform like Heroku or Ngrok. That's it @Nibba2018

**Comment by BALaka-18** [comment]
@soumya997 awesome idea ! We can develop a web application with two pages : One for user interactive analysis dashboards, and the other for prediction(model deployment). Let's carry this forward once the other PRs come in.

**Comment by soumya997** [comment]
yeah, sure @BALaka-18 😃

**Comment by soumya997** [comment]
> @soumya997 awesome idea ! We can develop a web application with two pages : One for user interactive analysis dashboards, and the other for prediction(model deployment). Let's carry this forward once the other PRs come in.

@Nibba2018 I guess you was talking about this, what the webapp will do?
I am really a dumb guy, sorry I did not get you at that beginning.

**Comment by Nibba2018** [comment]
@soumya997 If you are confident with your idea go ahead and make a PR.

**Comment by soumya997** [comment]
sure, @Nibba2018 
@BALaka-18 and @Nibba2018 I might be able to do the model prediction part but i have no idea how to make the user interactive analysis dashboard. So, if you guys can shear any resource then it would be very helpful for me.

**Comment by BALaka-18** [comment]
> sure, @Nibba2018
> @BALaka-18 and @Nibba2018 I might be able to do the model prediction part but i have no idea how to make the user interactive analysis dashboard. So, if you guys can shear any resource then it would be very helpful for me.

I'll work with along with you for the analysis part.

**Comment by soumya997** [comment]
Still would like to have some advice/resources from you @BALaka-18 for the analysis part

**Comment by BALaka-18** [comment]
> Still would like to have some advice/resources from you @BALaka-18 for the analysis part

Yes will share with you.

**Comment by soumya997** [comment]
@Nibba2018 @BALaka-18 as @khanfarhan10 has closed his PR, so I have tried to solve this issue #10 by making a web app. @BALaka-18 I am really sorry, but I have added the analysis page in my app, I hope you don't mind.
This is the app Link -> https://ffp-web-app.herokuapp.com/. If any changes are required please let me know.
This is going to be my 4th contribution of HF so if you guys can quickly(as its already 26th) look into the matter and approve it then I would like to push the code. I have added some animation after the prediction is done and Github profile cards of each contributor on the `contributors` page.

Now the whole app is based on one single python file, but to deploy that I had to add some other files too, and the CSV and the pickle file are also there. So, if I push the code, should I include those files in the PR, or only the python file and the link of the deployed app is ok?

**Comment by Nibba2018** [comment]
@soumya997 make a PR with all the files that you need to deploy the web app.

**Comment by soumya997** [comment]
OK, 
so before making the PR it would be very helpful if you can review the commands that are needed to make the PR without any conflicts.
This is the current summary of my local version of the  repo:
<br>
<img src="https://i.ibb.co/JcJWyRt/Screenshot-639.png">
<br>

# Steps:

**1st**. As the remote version of the repo is already added using `git remote add dsc-iem <link>` so this time I can skip this part.
**2nd**. `git pull dsc-iem master` to pull the changes from the remote repo.
**3rd**. add the files(deployment-related) in the local version via copy-pasting
**4th**. create a new branch `git -b checkout <branch-name>` and go the branch using `git checkout <branch-name>`.
**5th**. `git add .` and `git commit -m "<message>"` then `git push origin <branch-name>`.
**6th**. go to my forked version of the repo and make the PR.

Are these steps ok @Nibba2018 ?

**Comment by Nibba2018** [comment]
@soumya997 Overall the steps look good to me and should work. Just make sure to do `git push origin --set-upstream origin <branch-name>` on step 5.

**Comment by Nibba2018** [comment]
@soumya997 Also before doing step 2 you need to do `git fetch dsc-iem master`

**Comment by soumya997** [comment]
Do I also have to do`git merge` If I do `git fetch`?

**Comment by Nibba2018** [comment]
@soumya997 No just doing `git pull dsc-iem master` will do.

**Comment by soumya997** [comment]
So in the 2nd step, I will do `git pull dsc-iem master` only. Thanks for confirming
 You mentioned `git pull` in your video too.

**Comment by Nibba2018** [comment]
@soumya997 Yes
