### ISSUE TITLE
Create a Pull request Template file

### ISSUE THREAD

**Issue by BALaka-18** [dsc-iem/AI-Hacktoberfest#7]
## Description
Create a PULL_REQUEST_TEMPLATE.md file that must contain the skeleton of a PR description and generate the template each time a PR is created.

If you don't know how or what a PR template is, [read this link on creating Pull request templates](https://blog.axosoft.com/enhancing-pull-request-descriptions-templates/)

## Acceptance Criteria
- [ ] PULL_REQUEST_TEMPLATE.md file must be properly created.
- [ ] All instructions provided in the Description must be strictly followed.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Time Estimation
30 minutes

**Comment by debangeedas** [comment]
Hey I would like to give it a shot!

**Comment by BALaka-18** [comment]
> Hey I would like to give it a shot!

Sure why not. If you're unsure about what to keep in the template, you can comment here. Assigning you.

**Comment by debangeedas** [comment]
Could you please tell me what the template is about? I need more details to really understand what is required.

**Comment by BALaka-18** [comment]
> Could you please tell me what the template is about? I need more details to really understand what is required.

@debangeedas there's a link in the issue description. Kindly go through it, it has all the steps easily explained. If you have queries after that, contact me on Discord.

**Comment by debangeedas** [comment]
What should the TODO items be? Should they be the steps of how to create a PR or is it something else?

**Comment by BALaka-18** [comment]
> What should the TODO items be? Should they be the steps of how to create a PR or is it something else?

@debangeedas It'll be like **[this](https://github.com/anitab-org/vms/blob/develop/PULL_REQUEST_TEMPLATE.md)**

**Comment by Nibba2018** [comment]
@debangeedas Updates?

**Comment by Nibba2018** [comment]
@debangeedas Oops my bad, there were no linked PRs so I thought it was incomplete.
